
name: github-tasks
on:
  repository_dispatch:
    types: [checks_suite_update]
jobs:

  Checks:

    runs-on: ubuntu-latest

    steps:
      #https://github.com/actions/github-script
      #https://octokit.github.io/rest.js/v18#checks
      #https://docs.github.com/en/rest/reference/checks
      - name: 'github.rest.checks.update()'
        uses: actions/github-script@v5
        id: check
        with:
          script: |            
            const base=context.payload.repository.html_url
            const payload=context.payload.client_payload
            core.notice(`details: ${base}/runs/${payload.check_run_id}`)
            github.rest.checks.update({
              ...payload,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

      # Used to send email ! :)
      # Why ? Well... by default user settings has the option
      # "Send notifications for failed workflows only" set
      # see https://github.com/settings/notifications
      - name: Invalidate worflow
        if: github.event.client_payload.conclusion == 'failure'
        uses: actions/github-script@v5
        with:
          script: core.setFailed(`Check failed`)
