
name: MyWorkflow

on:
  release:
    types:
      - created
  push:
    branches:
      - 'master'

jobs:

  prerequist:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/myaction
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Define TAG
        id: meta
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/.*\+$ ]]; then
            echo "::set-output name=tag::${GITHUB_REF:10:-1}"
          elif [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            echo "::set-output name=tag::latest"
          fi

      - name: Get the output time
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
          echo "The time was ${{ github.ref }}"
          echo "The time was ${{ steps.meta.outputs.tag }}"

          if [[ "${{ steps.meta.outputs.tag }}" == "latest" ]]; then
            echo "MASTER"
          elif [[ ! -z "${{ steps.meta.outputs.tag }}" ]]; then
            echo "RELEASE"
          else
            echo "NONE"
          fi

      - name: Master
        if: ${{ steps.meta.outputs.tag && steps.meta.outputs.tag == 'latest' }}
        run: echo "master"

      - name: Release
        if: ${{ steps.meta.outputs.tag && steps.meta.outputs.tag != 'latest' }}
        run: echo "master"

      - name: None
        if: ${{ ! steps.meta.outputs.tag }}
        run: echo "master"

      - name: Create "Publish" check
        uses: actions/github-script@v5
        with:
          script: |
            const {status, data} = await github.rest.checks.create({
              name: 'Publish',
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              status: 'queued'              
            })
            console.log({ status })
            console.log(`created check: ${context.payload.repository.html_url}/runs/${data.id}`)
