
name: on-firefox-extension-signed
on:
  repository_dispatch:
    types: [on-firefox-extension-signed]
jobs:

  Job1:

    runs-on: ubuntu-latest

    steps:      
      - name: 'step1-'
        uses: actions/github-script@v5
        with:
          script: |            
            const client_payload=context.payload.client_payload            
            console.log(client_payload)
