
name: Test

on:
  push

jobs:

  Test:
    if: True
    runs-on: ubuntu-latest
    steps:

      - name: Get github check
        if: false
        uses: actions/github-script@v5
        with:
          script: |
            const { data } = await github.rest.checks.get({
              check_run_id: 3792356584,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            console.log(data)

      - name: test share var with script
        if: true
        uses: actions/github-script@v5
        id: thisStep
        with:
          script: |
            core.setOutput("foo", "hello world");

      - name: read var
        run: |
          echo '$GITHUB_SHA'
          echo '${GITHUB_SHA}'
          echo "foo = ${{ steps.thisStep.outputs.foo }}"

      - name: test share var with script
        uses: actions/github-script@v5
        with:
          script: |
            const payload = JSON.stringify(context.payload, undefined, 2)
            console.log(`The event payload: ${payload}`);
