
name: worflow1

on:
  push:
    branches:
      - 'master'
  
  repository_dispatch:
    types: [MyEvent]

jobs:

  job1:

    runs-on: ubuntu-latest

    steps:

      - name: step1
        run: |          
          echo "::debug::Hi there!"
