
name: worflow1

on:
  push:
    branches:
      - 'master'
    
jobs:

  job1:

    runs-on: ubuntu-latest

    steps:

      - name: step1
        run: |          
          echo ::set-output "coucou"
