
name: worflow2

on:
  
  repository_dispatch:
    types: [MyEvent]

jobs:

  job1:

    runs-on: ubuntu-latest

    steps:

      - name: step1
        run: |          
          echo "::debug::Hi there!"
          echo "::debug::payload: ${{ toJson(github.event.client_payload) }}"
      
      - name: script
        uses: actions/github-script@v3
          with:
            script: |
                console.log("This is a script");
