
name: worflow1

on:
  push:
    branches:
      - 'master'
jobs:

  job1:

    runs-on: ubuntu-latest

    steps:

      - name: step1
        run: |          
          echo "::debug::Hi there!"
          pwd
          ls

          id=$(curl -X 'POST' \
            "https://internals.ca.jdo-dev.org/job" \
            -H 'accept: application/json' \
            -H 'Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjMxMDc5NDEsImlzcyI6Imh0dHBzOi8vdXRpbGl0aWVzLmthZGlza2EuY29tLyIsImF1ZCI6Imh0dHBzOi8vdXRpbGl0aWVzLmthZGlza2EuY29tLyIsImlhdCI6MTYzMTU3MTk0MSwic3ViIjoiYXBpa2V5In0.kD70toP9EflHXqt6p4QpRSGhGEy8xQL_5YR4tR-cBhmQw8RPyqXxamL8xTFLvi9i35E9sRSK3AQUde2QImYDmw' \
            -H 'Content-Type: application/json' \
            -d '{ "script_name": "node.js" }')

          curl -X 'POST' \
            "https://internals.ca.jdo-dev.org/file?id=$id" \
            -H 'accept: application/json' \
            -H 'Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjMxMDc5NDEsImlzcyI6Imh0dHBzOi8vdXRpbGl0aWVzLmthZGlza2EuY29tLyIsImF1ZCI6Imh0dHBzOi8vdXRpbGl0aWVzLmthZGlza2EuY29tLyIsImlhdCI6MTYzMTU3MTk0MSwic3ViIjoiYXBpa2V5In0.kD70toP9EflHXqt6p4QpRSGhGEy8xQL_5YR4tR-cBhmQw8RPyqXxamL8xTFLvi9i35E9sRSK3AQUde2QImYDmw' \
            -H 'Content-Type: multipart/form-data' \
            -F 'file=@README.md;type=text/plain'

          curl -X 'PATCH' \
            "https://internals.ca.jdo-dev.org/job?id=$id" \
            -H 'accept: application/json' \
            -H 'Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjMxMDc5NDEsImlzcyI6Imh0dHBzOi8vdXRpbGl0aWVzLmthZGlza2EuY29tLyIsImF1ZCI6Imh0dHBzOi8vdXRpbGl0aWVzLmthZGlza2EuY29tLyIsImlhdCI6MTYzMTU3MTk0MSwic3ViIjoiYXBpa2V5In0.kD70toP9EflHXqt6p4QpRSGhGEy8xQL_5YR4tR-cBhmQw8RPyqXxamL8xTFLvi9i35E9sRSK3AQUde2QImYDmw' \
            -H 'Content-Type: application/json' \
            -d '{ "state": "IDLE" }'

