
name: worflow1


on:
  release:
    types:
      - created
  push:
    branches:
      - 'master'

jobs:

  prerequist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./myaction/action
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"          
