
name: worflow1


on:
  release:
    types:
      - created
  push:
    branches:
      - 'master'

jobs:

  prerequist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - uses: ./.github/actions/myaction
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
          echo "The time was ${{ github.ref }}"
          echo "The time was ${{ github.ref.substring(1, 3)  }}"
