
name: worflow1


on:
  release:
    types:
      - created
  push:
    branches:
      - 'master'

jobs:

  prerequist:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.step1.outputs.tag }}
    steps:
      - id: step1
        run: |
          echo "::debug::Hi there!"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.tag}}
