
name: worflow1


on:
  release:
    types:
      - created
  push:
    branches:
      - 'master'

jobs:

  prerequist:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/myaction
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Define TAG
        id: meta
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/.*\+$ ]]; then
            echo "::set-output name=tag::${GITHUB_REF:10:-1}"
          elif [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            echo "::set-output name=tag::latest"
          fi
          echo "::set-output name=tag::latest"

      - name: Get the output time
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
          echo "The time was ${{ github.ref }}"
          echo "The time was ${{ steps.meta.outputs.tag }}"

          if [[ ${{ steps.meta.outputs.tag }} == "latest" ]]; then
            echo "MASTER"
          elif [[ ! -z ${{ steps.meta.outputs.tag }} ]]; then
            echo "RELEASE"
          fi

