
name: worflow1


on:
  release:
    types:
      - created
  push:
    branches:
      - 'master'

jobs:

  prerequist:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: ./.github/actions/myaction
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'

      - id: meta
        run: |
          TAG=
          if [[ $GITHUB_REF =~ ^refs/tags/.*\+$ ]]; then
            TAG=${GITHUB_REF:10:-1}
          elif [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            TAG=latest
          fi

      - name: Get the output time
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
          echo "The time was ${{ github.ref }}"
          echo "The time was ${{ steps.meta.outputs.tag }}"
