
name: worflow1


on:
  release:
    types:
      - created
  push:
    branches:
      - 'master'

jobs:

  prerequist:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/myaction
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Define TAG
        id: meta
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/.*\+$ ]]; then
            echo "::set-output name=tag::${GITHUB_REF:10:-1}"
          elif [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            echo "::set-output name=tag::latest"
          fi
          #echo "::set-output name=tag::latest"

      - name: Get the output time
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
          echo "The time was ${{ github.ref }}"
          echo "The time was ${{ steps.meta.outputs.tag }}"

          if [[ "${{ steps.meta.outputs.tag }}" == "latest" ]]; then
            echo "MASTER"
          elif [[ ! -z "${{ steps.meta.outputs.tag }}" ]]; then
            echo "RELEASE"
          else
            echo "NONE"
          fi

      - name: Master
        if: ${{ steps.meta.outputs.tag && steps.meta.outputs.tag == 'latest' }}
        run: echo "master"

      - name: Release
        if: ${{ steps.meta.outputs.tag && steps.meta.outputs.tag != 'latest' }}
        run: echo "master"

      - name: None
        if: ${{ ! steps.meta.outputs.tag }}
        run: echo "master"

      - uses: actions/github-script@v4
        with:
          script: |
            console.log(context.payload.client_payload)
            core.warning('Something went wrong, but it\'s not bad enough to fail the build.')
            core.notice('commit: https://github.com/chtimi59/empty/commit/6bb1e09932766ad748e0cc226eb8102fb8b77268')
            core.notice('commit: [8b77268](https://github.com/chtimi59/empty/commit/6bb1e09932766ad748e0cc226eb8102fb8b77268)')
            core.notice(`commit: ${context.payload.repository.html_url}/commit/6bb1e09932766ad748e0cc226eb8102fb8b77268`)
            github.checks.create({
              head_sha: '6bb1e09932766ad748e0cc226eb8102fb8b77268',
              name: "Hello"
            })

