
name: worflow1


on:
  release:
    types:
      - created
  push:
    branches:
      - 'master'

jobs:

  prerequist:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.step1.outputs.tag }}
    steps:
      - id: step1
        run: |
        if [[ $GITHUB_REF == refs/tags/*+ ]]; then
          echo "::set-output name=TAG::release"
        elif [[ $GITHUB_REF == 'refs/heads/master' ]]; then
          echo "::set-output name=TAG::latest"
        fi        

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.tag}}
            